/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountingJournalItem } from './accountingJournalItem';


export interface AccountingJournal {
    ID?: string;
    documentID?: string;
    type?: string;
    applicationDate?: Date;
    creationDate?: Date;
    number?: number;
    locationID?: string;
    periodType?: string;
    items?: Array<AccountingJournalItem>;
}
