/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountingJournalItem } from './accountingJournalItem';


export interface AccountingJournal {
    ID?: string;
    DocumentID?: string;
    Type?: string;
    ApplicationDate?: Date;
    CreationDate?: Date;
    Number?: number;
    LocationID?: string;
    PeriodType?: string;
    Items?: Array<AccountingJournalItem>;
}
