/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ClientDetails {
    ID?: string;
    RFC?: string;
    legalName?: string;
    commercialName?: string;
    creditDays?: number;
    creditAmount?: number;
    paymentMethod?: string;
    creationDate?: Date;
    status?: string;
    salesContact?: string;
    creditContact?: string;
    loctaion?: string;
    comments?: string;
    priceList?: string;
    paymentTermType?: string;
    email?: string;
    telephones?: string;
    number?: number;
    accountNumber?: string;
    defaultDiscount?: number;
    clientSource?: string;
    account?: string;
}
