/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EditProduct {
    ID: string;
    Code: string;
    Title: string;
    Cost: number;
    CurrencyID: string;
    ExchangeRate?: number;
    SKU?: string;
    Description?: string;
    CostType?: number;
    Category1ID?: string;
    Category2ID?: string;
    Category3ID?: string;
    ChargeVAT?: boolean;
    Number?: number;
    PricingType?: number;
    Unit?: string;
    PurchaseType?: number;
    IEPSRate?: number;
    Type?: number;
    ProductionAuto?: boolean;
}
