/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EditProduct {
    ID: string;
    code: string;
    title: string;
    cost: number;
    currencyID: string;
    exchangeRate?: number;
    SKU?: string;
    description?: string;
    costType?: number;
    category1ID?: string;
    category2ID?: string;
    category3ID?: string;
    chargeVAT?: boolean;
    number?: number;
    pricingType?: number;
    unit?: string;
    purchaseType?: number;
    iEPSRate?: number;
    type?: number;
    productionAuto?: boolean;
}
