/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IEdmTypeReference } from './iEdmTypeReference';
import { RangeVariable } from './rangeVariable';
import { SingleValueNode } from './singleValueNode';


export interface FilterClause {
    Expression?: SingleValueNode;
    RangeVariable?: RangeVariable;
    ItemType?: IEdmTypeReference;
}
