/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FilterClause } from './filterClause';
import { FilterQueryValidator } from './filterQueryValidator';
import { ODataQueryContext } from './oDataQueryContext';


export interface FilterQueryOption {
    Context?: ODataQueryContext;
    Validator?: FilterQueryValidator;
    FilterClause?: FilterClause;
    RawValue?: string;
}
