/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IEdmType {
    TypeKind?: IEdmType.TypeKindEnum;
}
export namespace IEdmType {
    export type TypeKindEnum = 'None' | 'Primitive' | 'Entity' | 'Complex' | 'Row' | 'Collection' | 'EntityReference' | 'Enum';
    export const TypeKindEnum = {
        None: 'None' as TypeKindEnum,
        Primitive: 'Primitive' as TypeKindEnum,
        Entity: 'Entity' as TypeKindEnum,
        Complex: 'Complex' as TypeKindEnum,
        Row: 'Row' as TypeKindEnum,
        Collection: 'Collection' as TypeKindEnum,
        EntityReference: 'EntityReference' as TypeKindEnum,
        Enum: 'Enum' as TypeKindEnum
    }
}
