/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface IEdmSchemaElement {
    "SchemaElementKind"?: IEdmSchemaElement.SchemaElementKindEnum;
    "Namespace"?: string;
    "Name"?: string;
}

export namespace IEdmSchemaElement {
    export enum SchemaElementKindEnum {
        None = <any> 'None',
        TypeDefinition = <any> 'TypeDefinition',
        Function = <any> 'Function',
        ValueTerm = <any> 'ValueTerm',
        EntityContainer = <any> 'EntityContainer'
    }
}
