/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface IEdmType {
    "TypeKind"?: IEdmType.TypeKindEnum;
}

export namespace IEdmType {
    export enum TypeKindEnum {
        None = <any> 'None',
        Primitive = <any> 'Primitive',
        Entity = <any> 'Entity',
        Complex = <any> 'Complex',
        Row = <any> 'Row',
        Collection = <any> 'Collection',
        EntityReference = <any> 'EntityReference',
        Enum = <any> 'Enum'
    }
}
