/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ODataQueryContext } from './oDataQueryContext';


export interface InlineCountQueryOption {
    Context?: ODataQueryContext;
    RawValue?: string;
    Value?: InlineCountQueryOption.ValueEnum;
}
export namespace InlineCountQueryOption {
    export type ValueEnum = 'None' | 'AllPages';
    export const ValueEnum = {
        None: 'None' as ValueEnum,
        AllPages: 'AllPages' as ValueEnum
    }
}
