/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Inventory {
    Balance?: number;
    ClientOrdered?: number;
    CurrentInventory?: number;
    ID?: string;
    Location?: string;
    ProvidedOrdered?: number;
    SKU?: string;
    Title?: string;
    Value?: number;
    Code?: string;
}
