/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InvoiceListItem {
    "Serie"?: string;
    "Date"?: Date;
    "Number"?: number;
    "UUID"?: string;
    "ExpirationDate"?: Date;
    "ClientID"?: string;
    "ClientName"?: string;
    "RFC"?: string;
    "Cost"?: number;
    "Subtotal"?: number;
    "Discount"?: number;
    "VAT"?: number;
    "IEPS"?: number;
    "ISRRet"?: number;
    "VATRet"?: number;
    "Total"?: number;
    "Payments"?: number;
    "CreditNotes"?: number;
    "CurrencyID"?: string;
    "LocationID"?: string;
    "WarehouseID"?: string;
    "PriceListID"?: string;
    "CFDIID"?: string;
    "CFDIUse"?: number;
    "ExchangeRate"?: number;
    "VATRetRate"?: number;
    "Comments"?: string;
    "VATRate"?: number;
    "PurchaseOrder"?: string;
    "IsFiscalInvoice"?: boolean;
    "ShowIEPS"?: boolean;
    "Status"?: number;
}

