/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InvoiceDetailsProduct {
    productID?: string;
    name?: string;
    indexNumber?: number;
    code?: string;
    unit?: string;
    unitMultiplier?: number;
    qty?: number;
    price?: number;
    vATRate?: number;
    iEPSRate?: number;
    discount?: number;
    comments?: string;
    lotInfo?: string;
}
