/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewActivity {
    externalID?: string;
    externalIDType?: number;
    comment: string;
    startDate: Date;
    endDate: Date;
    eventType: string;
    isPublic: boolean;
    title: string;
    repeatable: boolean;
    repeatInterval?: number;
    repeatType?: number;
    repetitions?: number;
}
