/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewAddress } from './newAddress';


export interface NewClient {
    LegalName: string;
    CommercialName: string;
    RFC: string;
    CreditDays: number;
    CreditAmount: number;
    PriceListID: string;
    AccountingNumber: string;
    Email?: string;
    PaymentMethod?: number;
    PaymentTerm?: number;
    LocationID?: string;
    SalesEmployeeID?: string;
    CreditEmployeeID?: string;
    Comment?: string;
    Address?: NewAddress;
    Telephone?: string;
    AccountNumber?: string;
    DefaultDiscount?: number;
    Source?: string;
}
