/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewInvoicePayment } from './newInvoicePayment';
import { NewInvoiceProduct } from './newInvoiceProduct';
import { NewInvoiceService } from './newInvoiceService';


export interface NewInvoice {
    currencyID: string;
    exchangeRate?: number;
    iSRRetRate?: number;
    vATRetRate?: number;
    clientID?: string;
    locationID?: string;
    comments?: string;
    vATRate?: number;
    discountType?: number;
    discountAmount?: number;
    products?: Array<NewInvoiceProduct>;
    services?: Array<NewInvoiceService>;
    emails?: Array<string>;
    warehouseID?: string;
    purchaseOrder?: string;
    creditDays?: number;
    isFiscalInvoice?: boolean;
    showIEPS?: boolean;
    number?: number;
    cFDIUse?: number;
    account?: string;
    payments?: Array<NewInvoicePayment>;
    invoiceDate: Date;
    priceListID: string;
    serie?: string;
}
