/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface NewInvoiceProduct {
    "ID": string;
    "Price": number;
    "Qty": number;
    "Unit": string;
    "VAT"?: number;
    "IndexNumber"?: number;
    "IEPS"?: number;
    "IEPSType"?: number;
    "Comments"?: string;
    "VATExempt"?: boolean;
    "RequireLot"?: boolean;
    "SelectedImports"?: Array<string>;
    "OrderItemID"?: string;
}

