/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewInvoicePayment } from './newInvoicePayment';
import { NewInvoiceProduct } from './newInvoiceProduct';
import { NewInvoiceService } from './newInvoiceService';


export interface NewInvoice {
    CurrencyID: string;
    ExchangeRate?: number;
    ISRRetRate?: number;
    VATRetRate?: number;
    ClientID?: string;
    LocationID?: string;
    Comments?: string;
    VATRate?: number;
    DiscountType?: number;
    DiscountAmount?: number;
    Products?: Array<NewInvoiceProduct>;
    Services?: Array<NewInvoiceService>;
    Emails?: Array<string>;
    WarehouseID?: string;
    PurchaseOrder?: string;
    CreditDays?: number;
    IsFiscalInvoice?: boolean;
    ShowIEPS?: boolean;
    Number?: number;
    CFDIUse?: number;
    Account?: string;
    Payments?: Array<NewInvoicePayment>;
    InvoiceDate: Date;
    PriceListID: string;
    Serie?: string;
}
