/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewOrderService {
    ID: string;
    title: string;
    price: number;
    VAT?: number;
    qty: number;
    comments?: string;
    vATExempt?: boolean;
    indexNumber?: number;
    variableConcept?: boolean;
    orderItemID?: string;
}
