/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewProduct {
    Title: string;
    Cost: number;
    Price: number;
    CurrencyId: string;
    ExchangeRate?: number;
    Code: string;
    Description?: string;
    SKU?: string;
    Category1Id?: string;
    Category2Id?: string;
    Category3Id?: string;
    IEPS?: number;
}
