/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewService {
    code: string;
    title: string;
    currencyID: string;
    sATCompanyAccountID: string;
    measurementUnit: string;
    description?: string;
    category1ID?: string;
    category2ID?: string;
    category3ID?: string;
    variableConcept?: boolean;
    chargeVAT?: boolean;
}
