/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewService {
    Code: string;
    Title: string;
    CurrencyID: string;
    SATCompanyAccountID: string;
    MeasurementUnit: string;
    Description?: string;
    Category1ID?: string;
    Category2ID?: string;
    Category3ID?: string;
    VariableConcept?: boolean;
    ChargeVAT?: boolean;
}
