/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ODataRawQueryOptions {
    filter?: string;
    orderBy?: string;
    top?: string;
    skip?: string;
    select?: string;
    expand?: string;
    inlineCount?: string;
    format?: string;
    skipToken?: string;
}
