/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ODataQueryOptionsWebHook {
    "IfMatch"?: any;
    "IfNoneMatch"?: any;
    "Context"?: models.ODataQueryContext;
    "Request"?: any;
    "RawValues"?: models.ODataRawQueryOptions;
    "SelectExpand"?: models.SelectExpandQueryOption;
    "Filter"?: models.FilterQueryOption;
    "OrderBy"?: models.OrderByQueryOption;
    "Skip"?: models.SkipQueryOption;
    "Top"?: models.TopQueryOption;
    "InlineCount"?: models.InlineCountQueryOption;
    "Validator"?: models.ODataQueryValidator;
}

