/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrderDetailsProduct {
    ProductID?: string;
    Name?: string;
    IndexNumber?: number;
    Code?: string;
    Unit?: string;
    UnitMultiplier?: number;
    Qty?: number;
    Price?: number;
    IEPSRate?: number;
    Comments?: string;
    QtyFullFilled?: number;
    VATRate?: number;
}
