/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrderByNode {
    Direction?: OrderByNode.DirectionEnum;
}
export namespace OrderByNode {
    export type DirectionEnum = 'Ascending' | 'Descending';
    export const DirectionEnum = {
        Ascending: 'Ascending' as DirectionEnum,
        Descending: 'Descending' as DirectionEnum
    }
}
