/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface OrderByClause {
    "ThenBy"?: models.OrderByClause;
    "Expression"?: models.SingleValueNode;
    "Direction"?: OrderByClause.DirectionEnum;
    "RangeVariable"?: models.RangeVariable;
    "ItemType"?: models.IEdmTypeReference;
}

export namespace OrderByClause {
    export enum DirectionEnum {
        Ascending = <any> 'Ascending',
        Descending = <any> 'Descending'
    }
}
