/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductAlternativeUnits } from './productAlternativeUnits';
import { ProductInventories } from './productInventories';
import { ProductPrices } from './productPrices';


export interface ProductDetails {
    ID?: string;
    code?: string;
    title?: string;
    description?: string;
    creationDate?: Date;
    cost?: number;
    SKU?: string;
    comments?: string;
    costType?: number;
    category1ID?: string;
    category1?: string;
    category2ID?: string;
    category2?: string;
    category3ID?: string;
    category3?: string;
    currentInventory?: number;
    chargeVAT?: boolean;
    number?: number;
    pricingType?: number;
    unit?: string;
    currencyID?: string;
    currencyCode?: string;
    purchaseType?: number;
    iEPSRate?: number;
    type?: number;
    productionAuto?: boolean;
    prices?: ProductPrices;
    inventories?: Array<ProductInventories>;
    alternativeUnits?: Array<ProductAlternativeUnits>;
}
