/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ProductDetails {
    "ID"?: string;
    "Code"?: string;
    "Title"?: string;
    "Description"?: string;
    "CreationDate"?: Date;
    "Cost"?: number;
    "SKU"?: string;
    "Comments"?: string;
    "CostType"?: number;
    "Category1ID"?: string;
    "Category1"?: string;
    "Category2ID"?: string;
    "Category2"?: string;
    "Category3ID"?: string;
    "Category3"?: string;
    "CurrentInventory"?: number;
    "ChargeVAT"?: boolean;
    "Number"?: number;
    "PricingType"?: number;
    "Unit"?: string;
    "CurrencyID"?: string;
    "CurrencyCode"?: string;
    "PurchaseType"?: number;
    "IEPSRate"?: number;
    "Type"?: number;
    "ProductionAuto"?: boolean;
    "Prices"?: models.ProductPrices;
    "Inventories"?: Array<models.ProductInventories>;
    "AlternativeUnits"?: Array<models.ProductAlternativeUnits>;
}

