/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Product {
    ID?: string;
    Code?: string;
    Title?: string;
    Description?: string;
    CreationDate?: Date;
    Cost?: number;
    SKU?: string;
    Comments?: string;
    CostType?: number;
    CostTypeText?: string;
    Category1ID?: string;
    Category2ID?: string;
    Category3ID?: string;
    CurrentInventory?: number;
    ChargeVAT?: boolean;
    Number?: number;
    PricingType?: number;
    PricingTypeText?: string;
    Unit?: string;
    CurrencyID?: string;
    CurrencyCode?: string;
    PurchaseType?: number;
    PurchaseTypeText?: string;
    IEPSRate?: number;
    Type?: number;
    TypeText?: string;
    ProductionAuto?: boolean;
}
