/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ODataQueryContext } from './oDataQueryContext';
import { SelectExpandClause } from './selectExpandClause';
import { SelectExpandQueryValidator } from './selectExpandQueryValidator';


export interface SelectExpandQueryOption {
    Context?: ODataQueryContext;
    RawSelect?: string;
    RawExpand?: string;
    Validator?: SelectExpandQueryValidator;
    SelectExpandClause?: SelectExpandClause;
}
