/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Series {
    ID?: string;
    Serie?: string;
    StartNumber?: number;
    CurrentNumber?: number;
    Date?: Date;
    DocType?: number;
    DocTypeText?: string;
    Locations?: Array<string>;
}
