/**
 * Bind ERP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IEdmTypeReference } from './iEdmTypeReference';


export interface SingleValueNode {
    TypeReference?: IEdmTypeReference;
    Kind?: SingleValueNode.KindEnum;
}
export namespace SingleValueNode {
    export type KindEnum = 'None' | 'Constant' | 'Convert' | 'NonentityRangeVariableReference' | 'BinaryOperator' | 'UnaryOperator' | 'SingleValuePropertyAccess' | 'CollectionPropertyAccess' | 'SingleValueFunctionCall' | 'Any' | 'CollectionNavigationNode' | 'SingleNavigationNode' | 'SingleValueOpenPropertyAccess' | 'SingleEntityCast' | 'All' | 'EntityCollectionCast' | 'EntityRangeVariableReference' | 'SingleEntityFunctionCall' | 'CollectionFunctionCall' | 'EntityCollectionFunctionCall' | 'NamedFunctionParameter';
    export const KindEnum = {
        None: 'None' as KindEnum,
        Constant: 'Constant' as KindEnum,
        Convert: 'Convert' as KindEnum,
        NonentityRangeVariableReference: 'NonentityRangeVariableReference' as KindEnum,
        BinaryOperator: 'BinaryOperator' as KindEnum,
        UnaryOperator: 'UnaryOperator' as KindEnum,
        SingleValuePropertyAccess: 'SingleValuePropertyAccess' as KindEnum,
        CollectionPropertyAccess: 'CollectionPropertyAccess' as KindEnum,
        SingleValueFunctionCall: 'SingleValueFunctionCall' as KindEnum,
        Any: 'Any' as KindEnum,
        CollectionNavigationNode: 'CollectionNavigationNode' as KindEnum,
        SingleNavigationNode: 'SingleNavigationNode' as KindEnum,
        SingleValueOpenPropertyAccess: 'SingleValueOpenPropertyAccess' as KindEnum,
        SingleEntityCast: 'SingleEntityCast' as KindEnum,
        All: 'All' as KindEnum,
        EntityCollectionCast: 'EntityCollectionCast' as KindEnum,
        EntityRangeVariableReference: 'EntityRangeVariableReference' as KindEnum,
        SingleEntityFunctionCall: 'SingleEntityFunctionCall' as KindEnum,
        CollectionFunctionCall: 'CollectionFunctionCall' as KindEnum,
        EntityCollectionFunctionCall: 'EntityCollectionFunctionCall' as KindEnum,
        NamedFunctionParameter: 'NamedFunctionParameter' as KindEnum
    }
}
