export * from './accountingJournals.service';
import { AccountingJournalsService } from './accountingJournals.service';
export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './bankAccounts.service';
import { BankAccountsService } from './bankAccounts.service';
export * from './catalogs.service';
import { CatalogsService } from './catalogs.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './inventory.service';
import { InventoryService } from './inventory.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './prospects.service';
import { ProspectsService } from './prospects.service';
export * from './providers.service';
import { ProvidersService } from './providers.service';
export * from './services.service';
import { ServicesService } from './services.service';
export * from './warehouses.service';
import { WarehousesService } from './warehouses.service';
export * from './webHooks.service';
import { WebHooksService } from './webHooks.service';
export const APIS = [AccountingJournalsService, AccountsService, ActivitiesService, BankAccountsService, CatalogsService, ClientsService, CommentsService, InventoryService, InvoicesService, OrdersService, ProductsService, ProspectsService, ProvidersService, ServicesService, WarehousesService, WebHooksService];
