export * from './AccountingJournalsApi';
import { AccountingJournalsApi } from './AccountingJournalsApi';
export * from './AccountsApi';
import { AccountsApi } from './AccountsApi';
export * from './ActivitiesApi';
import { ActivitiesApi } from './ActivitiesApi';
export * from './BankAccountsApi';
import { BankAccountsApi } from './BankAccountsApi';
export * from './CatalogsApi';
import { CatalogsApi } from './CatalogsApi';
export * from './ClientsApi';
import { ClientsApi } from './ClientsApi';
export * from './CommentsApi';
import { CommentsApi } from './CommentsApi';
export * from './InventoryApi';
import { InventoryApi } from './InventoryApi';
export * from './InvoicesApi';
import { InvoicesApi } from './InvoicesApi';
export * from './OrdersApi';
import { OrdersApi } from './OrdersApi';
export * from './ProductsApi';
import { ProductsApi } from './ProductsApi';
export * from './ProspectsApi';
import { ProspectsApi } from './ProspectsApi';
export * from './ProvidersApi';
import { ProvidersApi } from './ProvidersApi';
export * from './ServicesApi';
import { ServicesApi } from './ServicesApi';
export * from './UserProfileApi';
import { UserProfileApi } from './UserProfileApi';
export * from './WarehousesApi';
import { WarehousesApi } from './WarehousesApi';
export * from './WebHooksApi';
import { WebHooksApi } from './WebHooksApi';
export const APIS = [AccountingJournalsApi, AccountsApi, ActivitiesApi, BankAccountsApi, CatalogsApi, ClientsApi, CommentsApi, InventoryApi, InvoicesApi, OrdersApi, ProductsApi, ProspectsApi, ProvidersApi, ServicesApi, UserProfileApi, WarehousesApi, WebHooksApi];
